---
- name: copy file
  hosts: all
 
  tasks:
 
  - name: Copy file remote
    template:
        src: files/restore.sh
        dest: /bin/sh/restore.sh
  - name: Execute the command in remote shell; stdout goes to the specified file on the remote.
    shell: restore.sh >> restore.txt
