---
- name: Copy files
  hosts: all
 
  tasks:
 
- name: Copy file with owner and permissions
    copy:
        src: /home/aperi/test.txt
        dest: /home/root/test.txt
        owner: root
        group: root
        mode: '0644'
