---
- name: copy file
  hosts: all
 
  tasks:
 
  - name: Copy file remote
    template:
        src: files/restore.sh
        dest: /home/root/restore.sh
        
  - name: Change the working directory to somedir/ before executing the command.
    shell: restore.sh >> restore.txt
    args:
      chdir: /home/root/
