---
- name: copy file
  hosts: all
 
  tasks:
 
  - name: Copy file remote
    template:
        src: files/restore.sh
        dest: /home/root/restore.sh
        
  - name: Execute the script
    command: sh /home/root/restore.sh
