---
- name: Copy files
  hosts: all
 
  tasks:
 
  - name: Copy ansible inventory file to client
    copy: src=/home/aperi/test.txt dest=/home/root/test.txt
            owner=root group=root mode=0777
